# Generated by Django 4.2.18 on 2025-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="posts_comme_user_id_5151d7_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_date"], name="posts_comme_created_e8bd2f_idx"
            ),
        ),
    ]
