# Generated by Django 4.2.18 on 2025-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_posts_comme_user_id_5151d7_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="posts_comme_user_id_5151d7_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "post"], name="posts_comme_user_id_480dac_idx"
            ),
        ),
    ]
