# Generated by Django 4.2.18 on 2025-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_comment_posts_comme_user_id_5151d7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="point",
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(("point__gte", 0), ("point__lte", 5)),
                name="point_between_0_to_5",
            ),
        ),
    ]
