# Generated by Django 4.2.18 on 2025-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_point_comment_point_between_0_to_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_dirty",
            field=models.BooleanField(default=True),
        ),
    ]
