# Generated by Django 4.2.18 on 2025-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_is_dirty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_dirty",
            field=models.BooleanField(default=False),
        ),
    ]
